### ISSUE TITLE
Attempting to use Discovery/Kubernettes getting errors when try to spin up K8 pods

### ISSUE THREAD

**Issue by JayneJacobs** [lreimer/advanced-cloud-native-go#1]
get pods
NAME                              READY   STATUS         RESTARTS   AGE
simplek8server-6b78ddcb9f-5gwln   0/1     ErrImagePull   0          38s
simplek8server-6b78ddcb9f-vljmg   0/1     ErrImagePull   0          38s

I am thinking I have to create the docker containers and push them to dockerhub but you don't mention that in the kubernetes section.

**Comment by lreimer** [comment]
Yes, you have to build the images for the server as well as the client. But you do not have to push them to Docker Hub. (you can of course)
- if you push the images to Docker Hub, you will have to modify the K8s deployment YAMLs to reflect the remote image name accordingly.

Suggestion to get things running locally:
- use the supplied `docker-compose.yml` file and issue: `docker-compose --build`
- now you have the images in your local registry
- you are running Kubernetes with Docker (activate it in Docker for Mac or Windows) you can use the images in your K8s deployments
- you should now be able to start the pods

Hope this makes sense.

**Comment by JayneJacobs** [comment]
I did build it and tagged it also thinking this was the case, I also tagged them and pushed them to docker hub. I am seeing this when I use 
 ``` kubectl get ev```
```image "simplek8server:1.0.1": rpc error: code = Unknown desc = Error response from daemon: pull access denied for simplek8server, repository does not exist or may require 'docker login'```

**Comment by JayneJacobs** [comment]
Here is my git hub link
https://github.com/JayneJacobs/advancedCloudNativeGo.git

How can I delete the pods and start over. I have been using minikube stop and minikube delete. Is there an easier way?

**Comment by JayneJacobs** [comment]
I changed the names to make sure it was different from your files. That is intentional, just so you know I have these containers
 ```
simplek8client               1.0.1               691df8cf38e5        45 minutes ago      263MB
jaynejacobs/simplek8client   1.0.1               691df8cf38e5        45 minutes ago      263MB
jaynejacobs/simplek8server   1.0.1               a04a8b474e95        45 minutes ago      263MB
simplek8server               1.0.1               a04a8b474e95        45 minutes ago      263MB
```

**Comment by JayneJacobs** [comment]
Anyway, I really appreciate the quick response

**Comment by lreimer** [comment]
If you use Minikube can use the following command, so that Docker build commands go directly against the daemon inside the Minikube VM
```bash
minikube docker-env
```
